### ISSUE TITLE
Switch to poetry

### ISSUE THREAD

**Issue by nlessmann** [MIDL-Conference/midl-website-builder#3]
The builder and the website repositories are currently using a mix of setuptools and pipenv. These two packages could both be replaced by poetry.

**Comment by HKervadec** [comment]
For what it's worth, it is also quite easy to package (due to the small number of up-to-date dependencies).

For instance, I use the following PKGBUILD for pacman:
```
# Maintainer: Hoel Kervadec <hoel@kervadec.bzh>

pkgname=midl-website-builder
pkgver=1.11
pkgrel=1
pkgdesc='MIDL website builder (mwb)'
arch=('x86_64')
url="https://github.com/MIDL-Conference/midl-website-builder"
license=('GPL')
depends=('python' 'python-htmlmin' 'python-markdown' 'python-pyscss' 'python-beautifulsoup4')
makedepends=('python-setuptools')
source=("https://github.com/MIDL-Conference/midl-website-builder/archive/$pkgver.tar.gz")
sha256sums=('9b05d54ac3f7d8c8218ac70d28210a58bbbc58f9227d28d6d1614ba21df54776')

prepare() {
	cd $srcdir/$pkgname-$pkgver
}

build() {
	cd $srcdir/$pkgname-$pkgver

	python setup.py build
}

package() {
	cd $srcdir/$pkgname-$pkgver
	python setup.py install --root="$pkgdir/"
	install -Dm644 LICENSE.md "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
```

Having compiled packages for arch and debian based distributions could be nice, as a side of poetry. Github makes it easy to add pre-compiled packages for releases.

**Comment by nlessmann** [comment]
Works fine for our purposes, no need to invest time into this.
